### ISSUE TITLE
braft-extensions-mentions

### ISSUE THREAD

**Issue by gtt011029** [ninesunsabiu/leetcode-cn-ts#1]
你好， braft-extensions-mentions还有在维护吗， 今天试了一下 braft-extensions-mentions， 好像有些问题，引用了 import 'braft-extensions/dist/emoticon.css';，但样式上还是怪怪的
![image](https://user-images.githubusercontent.com/45391413/192237827-df60066f-b005-4d82-9e53-1704bae8c54a.png)

https://github.com/margox/braft-extensions

**Comment by ninesunsabiu** [comment]
你好，这个 issue 请在 margox/braft-extensions#138 里面跟踪就可以了。 @gtt011029
